[
  {
    id: '67a711f0-2c6d-450a-904d-06ea25a3224c',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Платформа ', type: 'text', styles: {} },
      { text: 'Makala Box', type: 'text', styles: { bold: true } },
      {
        text: ' обладает удобными инструментами форматирования текста, позволяющими сделать ваш контент более выразительным и привлекательным для читателей. Для доступа ко всем этим инструментам достаточно нажать на клавишу "',
        type: 'text',
        styles: {},
      },
      { text: '/', type: 'text', styles: { bold: true } },
      {
        text: '", что вызовет выпадающее меню со всеми необходимыми инструментами (см. рисунок 1).',
        type: 'text',
        styles: {},
      },
    ],
    children: [],
  },
  {
    id: '87ebe117-3465-40b2-bbe0-2f1e6b3e38a4',
    type: 'image',
    props: {
      url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_19-15-58.png',
      width: 279,
      caption: 'Рисунок №1',
      textAlignment: 'center',
      backgroundColor: 'default',
    },
    children: [],
  },
  {
    id: '810b7fe4-0b10-4025-b49e-5935e1b3fa61',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Основное меню редактора.', type: 'text', styles: {} }],
    children: [],
  },
  {
    id: 'e7f19b93-bc26-4e14-8ccc-25e4a292eb0f',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Makala Box', type: 'text', styles: { bold: true } },
      {
        text: ' предоставляет удобную среду для написания, форматирования и публикации ваших исследований. Вы можете воспользоваться разнообразными инструментами, такими как:',
        type: 'text',
        styles: {},
      },
    ],
    children: [],
  },
  {
    id: '73e85927-e87a-4573-bb62-df9ae9abd784',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Заголовки (три уровня) ', type: 'text', styles: { bold: true } },
    ],
    children: [],
  },
  {
    id: '4aeadda4-6ca3-4e9c-b6ad-5e0a10814ea1',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Нумерованный список', type: 'text', styles: { bold: true } },
    ],
    children: [],
  },
  {
    id: '2e967ed1-b304-43ae-bfe3-4f385ff65f33',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Маркированный список', type: 'text', styles: { bold: true } },
    ],
    children: [],
  },
  {
    id: '0749bd00-51de-4580-a6c5-13106d170574',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Параграф', type: 'text', styles: { bold: true } }],
    children: [],
  },
  {
    id: '999d3c9b-9bf7-45c4-b0cf-4600df83bb26',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Таблица', type: 'text', styles: { bold: true } }],
    children: [],
  },
  {
    id: 'c2c70bbc-f513-49eb-9958-36f802912024',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Вставка изображений', type: 'text', styles: { bold: true } },
    ],
    children: [],
  },
  {
    id: '7151481c-0df3-4fa4-b880-c233a85a4d6d',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Заметки', type: 'text', styles: { bold: true } }],
    children: [],
  },
  {
    id: 'dc2a4fbf-4b96-4c15-bc08-8544d58ea6e2',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Форматирования Кода', type: 'text', styles: { bold: true } },
    ],
    children: [],
  },
  {
    id: 'bf7b6082-4a1d-49d9-9226-3d7087f8ee0b',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '57f09cfb-5e9e-4976-9799-b4a0189b2e93',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Заголовки:', type: 'text', styles: { bold: true } },
      { text: ' ', type: 'text', styles: {} },
    ],
    children: [],
  },
  {
    id: '5efb6c75-1d4d-49ce-bdcb-e87fb55e800e',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Позволяют создавать структурированное содержание с использованием разных уровней заголовков для организации текста.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: '699f7fae-8e7e-4a1c-879d-a662fab72793',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1. Нажать клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и выбрать уровень ', type: 'text', styles: {} },
          { text: 'заголовка', type: 'text', styles: { bold: true } },
          { text: '.', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: 'd5659a1d-2f6b-4e18-bc51-a83d6fd2d56e',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_20-42-59.png',
          width: 168,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: 'fdf02aa2-2508-4cb9-88e4-8a9a6d361da6',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: '10186eda-ad97-4fdc-960e-4a09cecfbbc4',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2. После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          {
            text: '", вы сможете начать вводить ваш ',
            type: 'text',
            styles: {},
          },
          { text: 'заголовок', type: 'text', styles: { bold: true } },
          { text: '.', type: 'text', styles: {} },
        ],
        children: [],
      },
    ],
  },
  {
    id: '6ef80a7b-55bb-486e-b239-04a79bd6dfe0',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: 'ffe9e5a9-11e6-4504-98b7-23110229a888',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '760d9fa2-2a3d-4286-b962-48c09ef45343',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Нумерованный список: ', type: 'text', styles: { bold: true } },
    ],
    children: [],
  },
  {
    id: '1a5b6bd1-f1b9-4dc7-ad07-936a01a5dd55',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Используется для перечисления элементов в определенном порядке с автоматическим присвоением номеров.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: '65bbc9f4-9644-458c-a34e-0ae3587651a4',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1. Нажать клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и выбрать инструмент "', type: 'text', styles: {} },
          { text: 'Нумерованный список', type: 'text', styles: { bold: true } },
          { text: '".', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '36ba05f0-a5a1-4c4d-ac71-e0a861eabda3',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_20-47-24.png',
          width: 171,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: '886ff342-470d-4ace-bc8b-593ae737a377',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: '87e3f8b4-54bf-440d-99de-3e596ae4e1b8',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2. После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          {
            text: '", вы сможете начать вводить данные в ',
            type: 'text',
            styles: {},
          },
          { text: 'нумерованный список', type: 'text', styles: { bold: true } },
          { text: '.', type: 'text', styles: {} },
        ],
        children: [],
      },
    ],
  },
  {
    id: '6e5f08f9-7337-42b2-a638-683c37664f99',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '9f9d7268-9a1f-4de8-a7bc-aafae2244f97',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '8488c126-220c-4ec2-93ba-aa741fe97ba0',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      { text: 'Маркированный список: ', type: 'text', styles: { bold: true } },
    ],
    children: [],
  },
  {
    id: '64306496-efe7-4cca-80aa-777a02a346d8',
    type: 'bulletListItem',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Позволяет создавать список элементов с помощью маркеров, не имеющих определенного порядка.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: 'e9e075e0-1a29-4a49-8061-68bb9b4fb94f',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1. Нажать клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и выбрать инструмент "', type: 'text', styles: {} },
          {
            text: 'Маркированный список',
            type: 'text',
            styles: { bold: true },
          },
          { text: '".', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '634e3a28-1b23-4f1c-9a3d-1854ecb2a6d9',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_20-51-48_gUdCDHK.png',
          width: 172,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: '183ed43b-390a-4be0-83e3-aa684d918609',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: 'a301b842-0aac-4b7d-b767-876aaf8d01ef',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2. После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          {
            text: '", вы сможете начать вводить данные в ',
            type: 'text',
            styles: {},
          },
          {
            text: 'маркированный список',
            type: 'text',
            styles: { bold: true },
          },
          { text: '.', type: 'text', styles: {} },
        ],
        children: [],
      },
    ],
  },
  {
    id: '09db9089-d376-4f2f-af5b-e0cbd7116d75',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '5aae1007-03a3-48eb-9fd3-6aa4dd5ac132',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '52a0fde2-fd58-4776-8954-49b7298fac2a',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Параграф: ', type: 'text', styles: { bold: true } }],
    children: [],
  },
  {
    id: 'd37a6eb7-4b76-4b1d-82f8-743c437a7d1f',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Это основная единица текста, обычно отделенная от других параграфов пустой строкой, используется для структурирования и организации текста.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: 'aeccf1b2-14ef-4feb-b887-fa3964d1a201',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1. Нажать клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и выбрать инструмент "', type: 'text', styles: {} },
          { text: 'Параграф', type: 'text', styles: { bold: true } },
          { text: '".', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '7b4097ba-8d6b-418b-a281-d3695c381b46',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_20-54-54.png',
          width: 145,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: 'f975200f-2464-44b4-a1b2-14f5fd89f0be',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: '1bbfd092-fa01-47fb-a6a7-597c72b1a92b',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2. После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          {
            text: '", вы сможете начать вводить текст.',
            type: 'text',
            styles: {},
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: '052bfde8-14d4-4269-821c-d2e145c00210',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '75f5f988-fd69-4384-b84e-1a4c2edf36f2',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '9316c301-5aca-4b72-8466-0cff7afec3e7',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Таблица: ', type: 'text', styles: { bold: true } }],
    children: [],
  },
  {
    id: '5c44c90e-63e8-422f-8f4c-e1e789cd8aab',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Позволяет организовать данные в виде таблицы с рядами и столбцами для лучшей визуализации информации.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: 'd75d7188-8cde-44f2-9365-294de1fb36be',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1.  Нажать клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и найти инструмент "', type: 'text', styles: {} },
          { text: 'Таблица', type: 'text', styles: { bold: true } },
          { text: '" ', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: 'e7dd85b4-0bea-4391-a8ee-73a2541f8194',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_19-48-10.png',
          width: 113,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: '61acedd3-8700-45a3-a4fa-41021b5c020a',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: '921457b7-1f74-4f3f-9dfd-8591a300d70a',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2. После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          {
            text: '", вы сможете начать вводить данные в созданную таблицу.',
            type: 'text',
            styles: {},
          },
        ],
        children: [],
      },
      {
        id: '9f76fd0b-2462-4e2a-97d5-3506c95584e6',
        type: 'table',
        props: { textColor: 'default', backgroundColor: 'default' },
        content: {
          rows: [
            {
              cells: [
                [{ text: 'Продукт', type: 'text', styles: { bold: true } }],
                [{ text: 'Цена', type: 'text', styles: { bold: true } }],
              ],
            },
            {
              cells: [
                [{ text: 'Яблоко', type: 'text', styles: {} }],
                [{ text: '$1.00', type: 'text', styles: {} }],
              ],
            },
            {
              cells: [
                [{ text: 'Банан', type: 'text', styles: {} }],
                [{ text: '$0.50', type: 'text', styles: {} }],
              ],
            },
            {
              cells: [
                [{ text: 'Апельсин', type: 'text', styles: {} }],
                [{ text: '$0.75', type: 'text', styles: {} }],
              ],
            },
          ],
          type: 'tableContent',
        },
        children: [],
      },
      {
        id: 'b63a94cd-a700-42bc-b127-42ad001dfdad',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          {
            text: '3. Нажав на кнопку над колонкой, вы можете ',
            type: 'text',
            styles: {},
          },
          { text: 'создать', type: 'text', styles: { bold: true } },
          { text: ' новую колонку ', type: 'text', styles: {} },
          { text: 'справа', type: 'text', styles: { bold: true } },
          { text: ' или ', type: 'text', styles: {} },
          { text: 'слева', type: 'text', styles: { bold: true } },
          { text: ', или же ', type: 'text', styles: {} },
          { text: 'удалить', type: 'text', styles: { bold: true } },
          { text: ' текущую колонку.', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '2d2b1db8-29aa-4f54-8b22-050541430e67',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/Group_2.png',
          width: 332,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: 'e1651e4e-d47f-4fe9-8787-4cf78c0d36e8',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          {
            text: '4. Нажав на кнопку слева от ряда, вы можете создать новый ряд ',
            type: 'text',
            styles: {},
          },
          { text: 'сверху', type: 'text', styles: { bold: true } },
          { text: ' или ', type: 'text', styles: {} },
          { text: 'снизу', type: 'text', styles: { bold: true } },
          { text: ', или же ', type: 'text', styles: {} },
          { text: 'удалить', type: 'text', styles: { bold: true } },
          { text: ' текущий ряд.', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '398f5c18-36fb-4b8e-aabd-5f8310ae481e',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: 'b5b59451-7a75-4b5f-aa72-479871575d16',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/Group_3.png',
          width: 258,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
    ],
  },
  {
    id: '7ed9a95d-60bb-46b4-842f-24ba68be81c3',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: 'a076e8bb-554d-4c45-8534-ffb4a8be6734',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '7bf92f02-1960-4c2b-904c-2b6407647275',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Изображения: ', type: 'text', styles: { bold: true } }],
    children: [],
  },
  {
    id: 'a5df1dba-0692-4bac-bf85-893d49e75611',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Позволяет вставлять графические файлы или изображения в документ для иллюстрации текста.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: '4358fb66-57f0-4042-94b0-7f2b885817a0',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1. Нажать на клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и найти инструмент "', type: 'text', styles: {} },
          { text: 'Изображения', type: 'text', styles: { bold: true } },
          { text: '"', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '760924fa-c8c5-4df8-9b01-e29d20fa7569',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_19-47-11.png',
          width: 157,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: '65930282-74d5-4c32-99da-6d04c1a0f88c',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: 'c5ce8c5f-71c2-4d67-aa0d-ebbbf27ee6e8',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2.  После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          {
            text: '", у вас появится окно, где вы сможете ',
            type: 'text',
            styles: {},
          },
          { text: 'загрузить', type: 'text', styles: { bold: true } },
          { text: ' или же ', type: 'text', styles: {} },
          { text: 'вставить адрес', type: 'text', styles: { bold: true } },
          { text: ' изображения.', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '157cd988-b43b-43ad-929f-a05bcef61ed1',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_20-26-42.png',
          width: 746,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: 'cb26d6f4-4f53-44ee-878e-4aa3a4210ada',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: '7740cd03-2182-47b4-b61d-8cd2c48f16b7',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '3. ', type: 'text', styles: {} },
          { text: 'Загрузка', type: 'text', styles: { bold: true } },
          {
            text: '(upload) изображения может занять какое-то время.',
            type: 'text',
            styles: {},
          },
        ],
        children: [],
      },
      {
        id: 'b4dc8212-acbf-438a-8735-6b07326b2b1c',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_20-32-06.png',
          width: 352,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: '9287a6e7-0ae8-46ac-a69f-2e8b581b183c',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: '1e7afdce-9641-4754-8190-16f0492335ce',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '4. Для ', type: 'text', styles: {} },
          { text: 'вставки адреса', type: 'text', styles: { bold: true } },
          {
            text: ' изображения просто выберите окно ',
            type: 'text',
            styles: {},
          },
          { text: 'Embed', type: 'text', styles: { bold: true } },
          { text: ' и вставьте ', type: 'text', styles: {} },
          { text: 'ссылку', type: 'text', styles: { bold: true } },
          { text: ' на изображение.', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: 'eef55c2e-fc97-4b51-83d1-3e58247f9c5b',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_20-36-41.png',
          width: 360,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
    ],
  },
  {
    id: '7f6300d6-eabf-47a1-8823-200bec74b25e',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '60fc9245-5249-4908-906d-41a1761118df',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: '76fcf844-a3be-4d8d-a90d-a66ab9c3bf0f',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Заметки', type: 'text', styles: {} }],
    children: [],
  },
  {
    id: 'e8a97e62-0309-4615-9fb4-ffc2c95cc238',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Инструмент, позволяющий добавлять краткие пометки или комментарии к тексту для уточнения информации или предоставления дополнительных пояснений.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: '911484ff-bd01-401a-9579-59c57441b6c4',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1. Нажать на клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и найти инструмент "', type: 'text', styles: {} },
          { text: 'Заметки', type: 'text', styles: { bold: true } },
          { text: '".', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '9300cdc0-c02b-4654-9e95-1aaac0ec1d43',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_21-13-39.png',
          width: 140,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: '2c6ced6c-2788-40e3-bb2d-cc38691621c0',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: 'be0fac45-67a0-483a-bb40-5b156eda0bcd',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2. После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          { text: '", у вас появится ', type: 'text', styles: {} },
          {
            text: 'информационная заметка ',
            type: 'text',
            styles: { bold: true },
          },
          { text: '(по умолчанию).', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '36ad5aa1-04a4-4755-899b-579dd291c892',
        type: 'alert',
        props: { type: 'info', textColor: 'default', textAlignment: 'left' },
        content: [],
        children: [],
      },
      {
        id: '0fb27e67-7389-48f8-aec9-d562ce8763ba',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: 'c4b72e75-cb68-43cb-aadd-0adc05f6b4fa',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '3. Вы можете ', type: 'text', styles: {} },
          { text: 'поменять тип', type: 'text', styles: { bold: true } },
          {
            text: ' "Заметки", нажав на иконку слева. При смене типа поменяется ',
            type: 'text',
            styles: {},
          },
          { text: 'стилистика', type: 'text', styles: { bold: true } },
          { text: ' и ', type: 'text', styles: {} },
          { text: 'иконка', type: 'text', styles: { bold: true } },
          { text: ' "Заметки".', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '5c3d0095-188c-4b38-aa03-7a40b3730b73',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/Group_4.png',
          width: 205,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
    ],
  },
  {
    id: '3b385735-31cb-4fa1-bf80-b2ff786c47bb',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: 'edb3605e-62a7-4899-9ae9-2946fde64a11',
    type: 'table',
    props: { textColor: 'default', backgroundColor: 'default' },
    content: { rows: [{ cells: [] }], type: 'tableContent' },
    children: [],
  },
  {
    id: '9b3499c1-eb94-49e6-a114-dbcc9e896f3b',
    type: 'heading',
    props: {
      level: 3,
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [{ text: 'Код', type: 'text', styles: {} }],
    children: [],
  },
  {
    id: 'e9edf5e1-6dd9-46ff-b7ce-abb9c223b86a',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Используется для форматирования и выделения отрывков кода в тексте, делая его более читаемым и понятным.',
        type: 'text',
        styles: {},
      },
    ],
    children: [
      {
        id: '6563b2ea-ed06-4c0a-881e-81dda0baca8b',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '1. Нажать на клавишу "', type: 'text', styles: {} },
          { text: '/', type: 'text', styles: { bold: true } },
          { text: '" и найти инструмент "', type: 'text', styles: {} },
          { text: 'Code', type: 'text', styles: { bold: true } },
          { text: '".', type: 'text', styles: {} },
        ],
        children: [],
      },
      {
        id: '5d30b543-e1da-45ca-b958-fca207323f0d',
        type: 'image',
        props: {
          url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_21-15-40.png',
          width: 109,
          caption: '',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        children: [],
      },
      {
        id: '629d3e1f-26c8-46ed-b076-d33b0dc767cc',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [],
        children: [],
      },
      {
        id: 'f78cbcd1-1e65-4f72-b572-d338148ccf6c',
        type: 'paragraph',
        props: {
          textColor: 'default',
          textAlignment: 'left',
          backgroundColor: 'default',
        },
        content: [
          { text: '2. После нажатия клавиши "', type: 'text', styles: {} },
          { text: 'Enter', type: 'text', styles: { bold: true } },
          {
            text: '", вы сможете начать вводить код.',
            type: 'text',
            styles: {},
          },
        ],
        children: [],
      },
      {
        id: '0a24cae7-d1e3-4574-8269-bd66f2c890c1',
        type: 'procode',
        props: {
          data: 'def greet(name):\n    print("Привет, " + name + "!")\n    \ngreet("Мир")',
        },
        children: [],
      },
    ],
  },
  {
    id: '0e1290d0-1d15-46a7-9c07-d9536360e863',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: 'daa40064-07de-4c0e-a591-eadccef75a56',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
  {
    id: 'a73fd48d-f87a-4f4b-94fc-04813dc5b747',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [
      {
        text: 'Помимо основного выпадющего списка инструментов есть и дополнительная ',
        type: 'text',
        styles: {},
      },
      { text: 'панель инструментов, ', type: 'text', styles: { bold: true } },
      {
        text: 'которая всплвает при выделии текста (см. рисунок 2).',
        type: 'text',
        styles: {},
      },
    ],
    children: [],
  },
  {
    id: '8e0a4a51-3aa6-434e-9608-83696f753bc8',
    type: 'image',
    props: {
      url: 'http://makalabox.api.ustaz.online/media/body/images/2024/05/02/image_2024-05-02_21-05-27.png',
      width: 649,
      caption: 'Рисунок №2',
      textAlignment: 'center',
      backgroundColor: 'default',
    },
    children: [],
  },
  {
    id: '3a272b02-95fd-4c01-8835-58cf97063180',
    type: 'procode',
    props: { data: '' },
    children: [],
  },
  {
    id: 'e759aaf1-5b41-44c5-a249-875e908b7738',
    type: 'paragraph',
    props: {
      textColor: 'default',
      textAlignment: 'left',
      backgroundColor: 'default',
    },
    content: [],
    children: [],
  },
];
